WIP: stashing WIP on getting bootstrap to work
[strap.compiler] /Users/adriaan/git/scala/src/compiler/scala/tools/nsc/ast/parser/Scanners.scala:428: error: type mismatch;
[strap.compiler]  found   : Char
[strap.compiler]  required: ' '
[strap.compiler]             val last = if (charOffset >= 2) buf(charOffset - 2) else ' '
[strap.compiler]                                                ^