Revert "delay deconst"
This reverts commit b4e479323888ce03eb3f8268a86864803d60f431,
because it breaks bootstrapping:

```
[strap.reflect] Compiling 157 files to /Users/adriaan/git/scala/build/strap/classes/reflect
[strap.reflect] /Users/adriaan/git/scala/src/reflect/scala/reflect/internal/Printers.scala:677: error: type mismatch;
[strap.reflect]  found   : AnyVal
[strap.reflect]  required: Long
[strap.reflect]         List(IMPLICIT, CASE, LAZY, SEALED).foreach{flag => if (mods.hasFlag(flag)) print(s"${mods.flagBitsToString(flag)} ")}
[strap.reflect]                                                                             ^
[strap.reflect] /Users/adriaan/git/scala/src/reflect/scala/reflect/internal/Printers.scala:677: error: type mismatch;
[strap.reflect]  found   : AnyVal
[strap.reflect]  required: Long
[strap.reflect]         List(IMPLICIT, CASE, LAZY, SEALED).foreach{flag => if (mods.hasFlag(flag)) print(s"${mods.flagBitsToString(flag)} ")}
[strap.reflect]                                                                                                                    ^
```